language: node_js
node_js:
  - "6"
  - "8"

install: yarn install

script:
  - yarn lint
  - yarn test
  - yarn codecov
  - yarn clean && yarn build
  - yarn build:examples-only && yarn check:examples
after_success:
- bash <(curl -s https://codecov.io/bash)

cache: yarn

notifications:
  email: never
  slack:
    rooms:
      - vega-js:3wQHcSva0iAMeHF2x30X2oGJ
    on_success: never
    on_failure: change
